# Generated by Django 5.2.14 on 2026-08-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_food_foodlog_foodlogentry_foodlog_foods_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
