# Generated by Django 6.0.6 on 2026-07-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('move_cal', models.IntegerField(default=0)),
                ('move_goal', models.IntegerField(default=500)),
                ('exercise_min', models.IntegerField(default=0)),
                ('exercise_goal', models.IntegerField(default=30)),
                ('stand_hrs', models.IntegerField(default=0)),
                ('stand_goal', models.IntegerField(default=12)),
                ('calories', models.IntegerField(default=0)),
                ('weight', models.FloatField()),
                ('water_cups', models.IntegerField(default=0)),
                ('water_goal', models.IntegerField(default=8)),
                ('steps', models.IntegerField(default=0)),
                ('steps_goal', models.IntegerField(default=10000)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_weight', models.FloatField()),
                ('target_weight', models.FloatField()),
                ('weeks_total', models.IntegerField()),
                ('weeks_in', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('duration_min', models.IntegerField()),
                ('calories', models.IntegerField()),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
